### PR TITLE
Using Mousetrap in ExportData

### PR DESCRIPTION
**Pull request by fracarma**
I have used this library (https://github.com/ccampbell/mousetrap) in order to solve a bug on my Chrome for Linux version. I was not able to use any shortcut in the Export Data page.

The library can be interesting also for creating more configurable shortcuts on the extension.

### CODE REVIEW

**Comment by jesperkristensen** [comment]
Thank you very much for you pull request. I have a few suggestions though.

I am a little worried by adding another third-party library. According to https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews Mozilla does not allow "Use unvetted third-party code libraries or frameworks" in Firefox add-ons, without saying which ones are vetted.

So if we can find out what this library does and implement it directly, I think that would be better. I think it would end up being only a few lines of code.

If we do add the library, I think we need the source version and not the minified one, to get it a better chance of passing Mozilla review.

You include the library in both dataExport.html and in the content script, but you don't use it in the content script. Content scripts are generally very performance sensitive, so we should include as little JS code as possible in them.

**Comment by fracarma** [comment]
Hi Jesper,
I added the library thinking on adding some other shortcuts on the extension. I use it on a daily basis and some other shortcuts would make it perfect, I will work on that.

If you prefer, I can fix just my bug and pull it to your repository and continuing on my version as a fork.

Last point: I made a mistake adding the library to the content! This is the first time I work on an extension and I confused a bit, I am sorry.

**Comment by jesperkristensen** [comment]
Ok, let's add the library then.

But please add the source version, and don't add it to the content script unless we need it there.

**Comment by fracarma** [comment]
I added the non-minified version of Moustrap and add an "Export shortcut" (ctrl+enter)

**Comment by jesperkristensen** [comment]
Sorry for the delay. I am quite busy with other things, so it will probably take a week or two before I look at this and merge it.

**Comment by jesperkristensen** [comment]
I just tried looking at your pull request. I can see that it is going to take me some time to understand how Mousetrap works.

**Comment by jesperkristensen** [comment]
I fixed it without using the library

**Comment by fracarma** [comment]
Ok, perfect... I will keep the library on my fork as I would like to implement dynamic shortcuts (for example, a choosable shortcut to save records on "view all page").

**Pull request closed without merging**
